Check ruby version 2
paketo-buildpacks/bundle-install pull request #157
Opened 2021-02-25 19:06 UTC by sophiewigmore

Signed-off-by: Forest Eckhardt <feckhardt@pivotal.io>

## Summary

Resolves #112. 

Performs a check on the Ruby version during each build by running `ruby --version` and checking if it differs from the previous build, if there was one. This should cover the case in which we rebuild an app with a different Ruby version (i.e. with `$BP_MRI_VERSION` set), but the `Gemfile` and `Gemfile.lock` stay the same. 

## Use Cases

This ensure that the cached `bundle-install` layer will NOT be reused if the Ruby version changes between builds.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have added an integration test, if necessary.

2021-02-25 23:34 UTC, ryanmoran requested changes
I'm not sure this was clear from the original issue, but I think that we only want to be rebuilding if the major or minor version changes. I was able to trigger a rebuild by only changing the patch version and I believe that is a bit too aggressive. Would it be possible to parse the version number and still reuse the cached layer if the change was only for a minor version bump?

2021-02-26 14:41 UTC, sophiewigmore commented
> Would it be possible to parse the version number and still reuse the cached layer if the change was only for a minor version bump?

Do you mean  reuse the cached layer if the change was a **patch**? But then trigger a rebuild on major/minor version changes?

2021-02-26 20:01 UTC, ryanmoran commented
@sophiewigmore yes. This is what I meant to say.

2021-02-26 22:38 UTC, ryanmoran requested changes

2021-02-26 22:38 UTC, ryanmoran commented on go.mod
> +	github.com/blang/semver v3.5.0+incompatible
```suggestion
```

I think this may have been pulled in accidentally.

2021-02-26 23:17 UTC, ryanmoran approved these changes

2021-02-26 23:17 UTC, merged